

"""it tells the operatioons can be performed on particular data items.

 x = "Hello World"	str	
 x = 20	int	
 x = 20.5	float	
 x = 1j	complex	
 x = ["apple", "banana", "cherry"]	list	
 x = ("apple", "banana", "cherry")	tuple	
 x = range(6)	range	
 x = {"name" : "John", "age" : 36}	dict	
 x = {"apple", "banana", "cherry"}	set	
 x = frozenset({"apple", "banana", "cherry"})	frozenset	
 x = True	bool	
 x = b"Hello"	bytes	
 x = bytearray(5)	bytearray	
 x = memoryview(bytes(5))	memoryview	
 x = None	NoneType
"""

brand = "chaitanya"
age = 22
float = 2.25
list = []
bool = "true"
set = {}
tuple = ()
dict = {"name" : "banana"}

print (type(brand))
print (type(age))
print (type(float))
print (type(list))
print (type(bool))
print (type(set))
print (type(tuple))
print (type(dict))